apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog
  namespace: liquibase
data:
  db.changelog-master.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
            http://www.liquibase.org/xml/ns/dbchangelog
            http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">

        <changeSet id="1_create_table" author="admin">
            <sqlFile path="1_create_table.sql"/>
        </changeSet>

        <changeSet id="2_insert_data" author="admin">
            <sqlFile path="2_insert_data.sql"/>
        </changeSet>

        <changeSet id="3_insert_data2" author="admin">
          <sqlFile path="3_insert_data2.sql"/>
        </changeSet>

        <changeSet id="4_delete_data" author="admin">
          <sqlFile path="4_delete_data.sql"/>
        </changeSet>

    </databaseChangeLog>
