apiVersion: v1
data:
  1_create_table.sql: |+
    -- 1_create_table.sql
    CREATE TABLE IF NOT EXISTS employees (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        position VARCHAR(100),
        salary DECIMAL
    );

  2_insert_data.sql: |+
    -- 2_insert_data.sql
    INSERT INTO employees (name, position, salary) VALUES
    ('Alice', 'Engineer', 75000),
    ('Bob', 'Manager', 90000);
  
  3_insert_data2.sql: |+
    -- 3_insert_data2.sql
    INSERT INTO employees (name, position, salary) VALUES
    ('Snehasish', 'Clerk', 15000);

  4_delete_data.sql: |+
    -- 4_delete_data.sql
    delete from employees where name='Alice';

  config-version: "v2.0"

kind: ConfigMap
metadata:
  name: liquibase-sql-files
  namespace: liquibase
