apiVersion: v1
kind: Pod
metadata:
  name: file-checker
  namespace: liquibase
spec:
  containers:
  - name: busybox
    image: 039765606255.dkr.ecr.us-east-1.amazonaws.com/busybox:latest
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: "/mnt/sql"
      name: sql-volume
  volumes:
  - name: sql-volume
    hostPath:
      path: /mnt/sql
